version: '3.8'
services:
  db:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - db:/data/db
  activemq:
    image: rmohr/activemq
    ports:
      - '8161:8161'
      - '61616:61616'
volumes:
  db:
    driver:
      local
